### ISSUE TITLE
Putting collars on cat = Missing Texture.

### ISSUE THREAD

**Issue by cassowarycasper** [sweetrpg/CatHerder#39]
## Environment And Mod Information:

* Minecraft Version: [i.e. 1.18.1] 1.18.2
* Forge Version: [i.e. 14.21.1.2443] 40.1.20
* Cat Herder Version: [i.e. 1.14.1.240] 0.75 Alpha
* Java Version: [i.e. 8 Update 144 64 bit] Java version 8
* Operating System (OS): [i.e. Windows 10 64-bit Build 17134] Windows 10 Home 64-bit Build 19044.1826

## Steps to reproduce:

1. Obtain modded training cat.
2. Repeatedly right click trying to put a dyed light blue wool collar on said training cat without success.
3. Right click with rainbow cat collar.
4. View black and purple missing textures.

## Additional Information:

- More Details: 
- Screenshots: 
![image](https://user-images.githubusercontent.com/77241013/181601871-37df9d58-d05b-4615-b1df-4321aa103425.png)

**Comment by paulyhedral** [comment]
Fixed in merge commit 2c4a96a29c691f43303dc31074854c01f9a35d72.
