### ISSUE TITLE
Continue development

### ISSUE THREAD

**Issue by OysterStew** [sweetrpg/CatHerder#40]
Like this mod. Have no issues thru .75 alpha other than missing textures for cosmetic items. Please continue developing this.

**Comment by paulyhedral** [comment]
See this comment: https://github.com/sweetrpg/CatHerder/issues/41#issuecomment-1849140652. :)

**Comment by paulyhedral** [comment]
4134f7c61ee52058953d78a856ef01db18b2a6ea
