### ISSUE TITLE
[Inquiry] Hey, is everything okay?

### ISSUE THREAD

**Issue by Cixon** [sweetrpg/CatHerder#41]
Not entirely sure if the project is abandoned or if you’re struggling with some sort of hardship but I’d love if you could get back to us on the Curseforge community. Opening comments would help immensely. This project is excellent and I want to see it thrive for 1.18 and future versions.

**Comment by laziwox** [comment]
yes I love this mod, personally I have a texture bug with my cat. 
![capturcatmin](https://user-images.githubusercontent.com/116454949/217072505-669ddb0f-117b-43f5-a5ca-10fb7fcfaf60.png)
And  I want a beautiful cat

**Comment by paulyhedral** [comment]
Hi guys!

Thanks for the encouragement and sorry for the long silence. Things have been going on. The project is not abandoned.

I have been making some updates to the project internally to support development on 1.18 and 1.20 simultaneously. There should hopefully be a 1.18 update soon, but I'm not sure yet about 1.20; there have been some significant changes to how rendering works between 1.18 and 1.20, so I'm trying to catch up with that. >.>

More soon.

**Comment by paulyhedral** [comment]
> yes I love this mod, personally I have a texture bug with my cat. ![capturcatmin](https://user-images.githubusercontent.com/116454949/217072505-669ddb0f-117b-43f5-a5ca-10fb7fcfaf60.png) And I want a beautiful cat

@laziwox Do you know which texture ID you chose that is showing the purple/black checkerboard?

**Comment by paulyhedral** [comment]
Figured this one out. The texture was broken when the collar is applied. Fixed now.
