### ISSUE TITLE
Catnip not harvesting

### ISSUE THREAD

**Issue by LoserCatDoesStuff** [sweetrpg/CatHerder#80]
## Environment And Mod Information:

* Minecraft Version: 1.18.2
* Forge Version:  40.2.0
* Cat Herder Version:  1.18.1.0.0
* Java Version: . 8 Update 381 
* Operating System (OS): Windows 11 OS Build: 22621.2861

## Issue Description:

Whenever I harvest the domestic catnip plant, it doesn't drop catnip, it only drops one catnip seed.

## Steps to reproduce:

1. Plant catnip seeds
2. use bonemeal to grow it/wait for it to grow
3. harvest fully grown catnip
4. no catnip leaves drop

## Additional Information:

- More Details: i also tried this on the previous 1.18 version
- Screenshots:

**Comment by paulyhedral** [comment]
Fixed in 98df8f73ad031a47aed063e348bf40a2a2f94608.
